<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'rapture\\acl\\acl' => '/../src/Acl.php',
                'rapture\\acl\\adapter\\php' => '/../src/Adapter/Php.php',
                'rapture\\acl\\definition\\adapterinterface' => '/../src/Definition/AdapterInterface.php',
                'rapture\\acl\\definition\\requesterinterface' => '/../src/Definition/RequesterInterface.php',
                'rapture\\acl\\definition\\resourceinterface' => '/../src/Definition/ResourceInterface.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
